config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  scope :users do
    resources :profiles, except: %i[index] do
      resources :collects, only: %i[create destroy]
    end
  end
  
  # articles
  resources :articles
  
  # comments 
  resources :cocktails do
    resources :comments
  end

  # classic cocktails
  resources :classic_cocktails

  # like
  get "likes/:cocktail_id", to: "likes#show"
  post "likes", to: "likes#create"

  # user location
  post "/get_user_location", to: "pages#get_user_location"

  # outher
  get "setting", to: "users#setting"
  get "cocktail_map", to: "pages#cocktail_map"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  before_create :generate_uuid_v7

  private

  def generate_uuid_v7
    return if self.class.attribute_types["id"].type != :uuid

    self.id ||= UUID7.generate
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, :category, :content, presence: true
end

app/models/classic_cocktail.rb
class ClassicCocktail < ApplicationRecord
  has_one_attached :image
  def self.ransackable_attributes(_auth_object = nil)
    %w[base_wine created_at garnish glass history id id_value ingredient method name skill updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_rich_text :introduce
  has_many_attached :images
  has_many :likes
  has_many :comments
  belongs_to :user

  def self.ransackable_attributes(_auth_object = nil)
    %w[name base_wine]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/models/collect.rb
class Collect < ApplicationRecord
  belongs_to :profile
  belongs_to :user

  validates :user_id, uniqueness: { scope: :profile_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail

  validates :user_id, uniqueness: { scope: :cocktail_id, message: "has already liked this cocktail" }
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_one_attached :avatar
  belongs_to :user
  has_many :collects
  has_many :followers, through: :collects, source: :user

  def address_info
    [["請選擇", nil], %w[台北市 台北市], %w[新北市 新北市], %w[桃園市 桃園市], %w[台中市 台中市], %w[台南市 台南市], %w[高雄市 高雄市], %w[新竹縣 新竹縣], %w[苗栗縣 苗栗縣], %w[彰化縣 彰化縣], %w[南投縣 南投縣], %w[雲林縣 雲林縣], %w[嘉義縣 嘉義縣], %w[屏東縣 屏東縣], %w[宜蘭縣 宜蘭縣], %w[花蓮縣 花蓮縣], %w[台東縣 澎湖縣], %w[金門縣 金門縣], %w[連江縣 連江縣], %w[基隆市 基隆市], %w[新竹市 新竹市], %w[嘉義市 嘉義市]]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :cocktails
  has_many :likes
  has_many :comments
  has_many :collects
  has_many :followed_profiles, through: :collects, source: :profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    user ||= User.create(full_name: data["name"],
                         email: data["email"],
                         password: Devise.friendly_token[0, 20],)
    user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show; end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "文章建立成功!"
    else
      flash.now[:alert] = @article.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "文章更新成功!"
    else
      flash.now[:alert] = @article.errors.full_messages
      render :edit
    end
  end

  def destroy; end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :category, :content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :check_current_user, only: [:create]

  def show
    cocktail = Cocktail.find(params[:cocktail_id])
    likes_count = cocktail.likes.count
    liked = cocktail.likes.exists?(user_id: current_user.id) if current_user.present?
    render json: {
      likes_count: likes_count,
      current_user_liked: liked,
    }
  end

  def create
    @like = Like.new(user_id: current_user.id, cocktail_id: params[:cocktail_id])
    if @like.save
    else
      destroy
    end
    show
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id)
    @like.delete
  end

  private

  def check_current_user
    redirect_to new_user_session_path if current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_profile, only: :home
  def home
    @cocktails = Cocktail.all
  end

  def cocktail_map; end

  def check_profile
    return if current_user.nil?
    return if current_user.profile.present?

    name = current_user.full_name || current_user.email
    current_user.create_profile(name: unique_name(name))
  end

  private

  def unique_name(name)
    "#{name}-#{SecureRandom.hex(4)}" # 在名称后面加上随机字符串
  end

  def default_avatar
    "https://cdn-icons-png.flaticon.com/512/149/149071.png"
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def show
    @user = User.find(@profile.user_id)
    @cocktails = Cocktail.where(user_id: @user.id)
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path(@profile.id), notice: "Profile was successfully created."
    else
      flash[:alert] = @profile.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path(@profile.id), notice: "Profile was successfully updated."
    else
      flash[:alert] = @profile.errors.full_messages
      render :edit
    end
  end

  def destroy; end

  private

  def profile_params
    params.require(:profile).permit(:name, :phone, :address, :descript, :avatar)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, olny: %i[show setting]
  before_action :authenticate_user!

  def show; end

  def setting; end

  private

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/collects_helper.rb
module CollectsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def search_bars(api_key, location, radius = 5000)
    url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=#{api_key}&location=#{location}&radius=#{radius}&keyword=bar")
    response = Net::HTTP.get(url)
    data = JSON.parse(response)
    puts data["results"]

    if data["status"] == "OK"
      data["results"]
    else
      []
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/_follow_button.html.erb
 <% if current_user && current_user.profile.id != params[:id] %>
  <div>
    <% if current_user.followed_profiles.include?(@profile) %>
      <%= button_to '追蹤中', profile_collect_path(@profile), method: :delete, class:"my-4 rounded-md text-gray-500 w-full", data: {turbo_confirm: "確定要取消追蹤嗎?"} %>
    <% else %>
      <%= button_to '追蹤', profile_collects_path(@profile), method: :post, class:" my-4 rounded-md bg-blue-500 p-1 w-full" %>
    <% end %>
  </div>
<% end %>

app/views/profiles/_form.html.erb
<%= form_with(model: @profile, data: {turbo: false}) do |f|%>
  <div class="relative my-2">
    <span class="absolute top-0 inline-flex w-2 h-2 bg-red-400 rounded-full opacity-75 left-8"></span>
    <%= f.label :name, "暱稱"%>
    <%= f.text_field :name, class:"w-full rounded-md p-2 text-black", placeholder: "ex: DOJO"%>
  </div>
  <div class="my-2">
    <%= f.label :phone, "電話"%>
    <%= f.text_field :phone,type: "tel", class:"w-full rounded-md p-2 text-black", placeholder:"0900123123"%>
  </div>
  <div class="my-2">
    <%= f.label :address, "所在地"%>
    <%= f.select :address, options_for_select(@profile.address_info, selected: @profile.address), {},{ class: "w-full rounded-md p-2 text-black" } %>
  </div>
  <div class="my-2">
    <%= f.label :descript, "簡介"%>
    <%= f.text_area :descript, rows: 15,  class:"w-full rounded-md p-2 text-black ", placeholder:"簡單的自我介紹，讓大家認識你吧!"%>
  </div>
  <%= f.submit "submit", class:"w-full rounded-md bg-amber-800 p-2 cursor-pointer hover:bg-amber-900"%>
<% end %>

app/views/profiles/_user_cocktails.html.erb
<div class="mt-4">
  <% if @cocktails.length == 0%>
    <p class="text-center text-gray-400">尚未擁有調酒</p>
    <%= link_to "新增調酒", new_cocktail_path, class:"p-2 rounded-md bg-amber-900 mx-auto block w-fit my-4" if current_user && current_user.id === @profile.user_id%>
  <% end %>
  <div class="grid grid-cols-3 gap-2">
    <% @cocktails.each do |cocktail|%>
      <%= link_to cocktail_path(cocktail.id) do %>
        <div class="w-full p-2 my-2 border border-gray-400 rounded-md hover:border-white">
          <%= image_tag cocktail.images.first.variant(resize_to_fill: [500, 500]), class:"w-full  mx-auto rounded-sm" if cocktail.images.attached?%>
          <div class="flex justify-between mt-2">
            <p class="font-bold"><%= cocktail.name%></p>
            <div class="flex gap-2">
              <p><%= cocktail.likes.count%> </p>
              <%= image_tag "icons/heart.svg"%>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="w-full ">
  <h2>Edit Profile</h2>
  <%= render "form" %>
</div>

app/views/profiles/new.html.erb
<div class="w-full ">
  <h2>建立個人檔案</h2>
  <%= render "form" %>
</div>

app/views/profiles/show.html.erb
<div>
  <%# edit_profile %>
  <% if  current_user && current_user.id === @profile.user_id  %>
    <%= link_to "編輯個人資料", edit_profile_path(current_user.profile.id) , class:"p-1 mx-auto my-2 text-gray-500 border border-gray-500 rounded-md hover:border-white hover:text-white w-fit  block" %>
  <% end %>
  <div class="grid items-center grid-cols-12">
    <div class="col-span-3" data-controller="upload-image">
      <div data-action="click->upload-image#selectImage">
        <% if @profile.avatar.attached? %>
          <div class="flex items-center justify-center mx-auto rounded-full w-fit">
            <%= image_tag @profile.avatar.variant(resize_to_limit: [500, 500]), class:"w-24 rounded-full"%>
          </div>
        <% else %>
          <div class="flex items-center w-16 h-16 mx-auto bg-white rounded-full md:w-24 lg:w-32 md:h-24 lg:h-32">
            <%= image_tag "icons/upload.svg", class:"mx-auto"%>
          </div>
        <% end %>
      </div>
      <%# upload_image %>
      <% if current_user && current_user.id === @profile.user_id %>
        <%= form_with(model: @profile, data: {turbo: false, turbo_method: :patch, upload_image_target: "form"}, class:"hidden") do |f|%>
          <%= f.file_field :avatar, data:{ upload_image_target: "input", action: "change->upload-image#uploadImage"}%>
        <% end %>
      <% end %>
    </div>
    <div class="col-span-9 ml-4 ">
      <h1>
        <%= @profile.name%>
      </h1>
    </div>
    <div class="col-span-12 ">
      <p class="overflow-auto max-h-32">
        <%= @profile.descript %>
      </p>
    </div>
  </div>
  <div class="grid grid-cols-12 gap-2 mt-4">
    <div class="col-span-4 p-2 text-center text-gray-400 border border-gray-400 rounded-md">
      <%= image_tag "icons/cocktail.svg" , class:"mx-auto"%>
      <p>調酒 <%= @cocktails.count%></p>
    </div>
    <div class="col-span-4 p-2 text-center text-gray-400 border border-gray-400 rounded-md">
      <%= image_tag "icons/heart.svg", class:"mx-auto"%>
      <p>喜歡 <%= @user.likes.count%> </p>
    </div>
    <div class="col-span-4 p-2 text-center text-gray-400 border border-gray-400 rounded-md">
      <%= image_tag "icons/collection.svg", class:"mx-auto"%>
      追蹤 <%= @profile.followers.count %> </div>
  </div>
  <%= render "follow_button"%>
  <%= render "user_cocktails"%>
</div>