config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  scope :users do
    resources :profiles, except: %i[index] do
      resources :collects, only: %i[create destroy]
    end
  end
  
  # articles
  resources :articles
  
  # comments 
  resources :cocktails do
    resources :comments
  end

  # classic cocktails
  resources :classic_cocktails

  # like
  get "likes/:cocktail_id", to: "likes#show"
  post "likes", to: "likes#create"

  # user location
  post "/get_user_location", to: "pages#get_user_location"

  # outher
  get "setting", to: "users#setting"
  get "cocktail_map", to: "pages#cocktail_map"
  
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_rich_text :introduce
  has_many_attached :images
  has_many :likes
  has_many :comments
  belongs_to :user

  def self.ransackable_attributes(_auth_object = nil)
    %w[name base_wine]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

require "image_processing/mini_magick"

class CocktailsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_cocktail, only: %i[show edit update destroy]

  def index
    @q = Cocktail.ransack(params[:q])
    @cocktials = @q.result
  end

  def show
    @comment = Comment.new
    @comments = Comment.includes(user: :profile).where(cocktail_id: params[:id])
    @likes = @cocktail.likes.count
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = current_user.cocktails.build(cocktail_params)

    if params[:cocktail][:images].present?
      params[:cocktail][:images].each do |image|
        next if image.blank?

        ok_image = resize_image(image, 1920, 1080)
        puts "** #{File.size(ok_image.path)}"
      end
    end

    if @cocktail.save
      redirect_to @cocktail, notice: "Cocktail was successfully created."
    else
      flash.now[:alert] = @cocktail.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(params[:id])
    else
      flash.now[:alert] = @cocktail.errors.full_messages
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :skill, :base_wine, :introduce, images: [])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def resize_image(image, max_width, max_height)
    pipeline = ImageProcessing::MiniMagick.source(image)
    pipeline.resize_to_limit!(max_width, max_height)
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<div data-controller="preview-img">
  <%= form_with(model: @cocktail, data:{ turbo: false }) do |f|%>
    <div class="my-2 ">
      <%= f.label :images, "相片" %>
      <%= f.file_field :images, multiple: true, id: "image-input", class: "w-full rounded-md", data: { target: "preview-img.input" }, accept: 'image/png,image/jpeg' %>
      <div id="image-preview" class="flex items-center gap-2"></div>
    </div>
    <div class="my-2 ">
      <%= f.label :name, "酒名" %>
      <%= f.text_field :name, class: "w-full rounded-md text-black" %>
    </div>
    <div class="my-2 ">
      <%= f.rich_text_area  :introduce, placeholder: "撰寫說明 / 製作方法" %>
    </div>
    <div class="my-2 ">
      <%= f.label :base_wine, "基酒" %>
      <%= f.select :base_wine, [["Whisky","Whisky"], ["Gin", "Gin"], ["Tequila", "Tequila"], ["Vodka", "Vodka"], ["Rum", "Rum"], ["Brandy", "Brandy"]], {}, { class: "w-full rounded-md text-black" } %>
    </div>
    <div class="my-2 ">
      <%= f.label :skill, "手法" %>
      <%= f.select :skill, [["Build", "Build"], ["Stir", "Stir"], ["Shake", "Shake"]], {}, { class: "w-full rounded-md text-black" } %>
    </div>
    <div class="p-1 my-4 text-center bg-gray-500 rounded-md">
      <%= f.submit "submit", class: "w-full" %>
    </div>
  <% end %>
</div>

app/views/cocktails/_likes.html.erb
<turbo-stream action="update" target="likes">
  <template>
    <%= likes%>
  </template>
</turbo-stream>

app/views/cocktails/edit.html.erb
<div>
  <h2 class="text-2xl">Edit Cocktail</h2>
  <%= render "form"%>
</div>

app/views/cocktails/index.html.erb
<div>
  <div class="flex items-center gap-4">
    <h1>創意調酒</h1>
    <%= link_to new_cocktail_path do%>
      <%= image_tag "icons/add.svg"%>
    <% end %>
  </div>
  <div class="my-4">
    <% if @cocktials.length === 0 %>
      <h2 class="text-center "> oops! 未找到相關資料 </h2>
    <% end %>
    <div class="grid grid-cols-3 ">
      <% @cocktials.each do |cocktail|%>
        <%= link_to cocktail_path(cocktail.id) do%>
          <div class="overflow-hidden border-2 rounded border-neutral-800">
            <div>
              <%= image_tag cocktail.images.first.variant(resize_to_fill:[500, 500])%>
              <p class="mx-1 "><%= cocktail.name%> </p>
            </div>
            <p class="mx-1 text-sm text-gray-400 truncate md:text-lg"><%= cocktail.user.profile.name%> </p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div>
  <%= link_to :back do %>
    <%= image_tag "arrow_back_icon.png", class:"invert"%>
  <% end %>
  <h1 class="mt-4 text-center">新增創意調酒</h1>
  <%= render "form"%>
</div>

app/views/cocktails/show.html.erb
<div class="relative show_cocktail">
  <div >
    <div class="absolute flex items-center justify-between w-full -top-10 ">
      <%= link_to cocktails_path , class:"invert " do%>
        <%= image_tag "arrow_back_icon.png"%>
      <% end %>
      <% if current_user && current_user.cocktails.find_by(id: @cocktail.id) %>
        <%= link_to "edit", edit_cocktail_path(@cocktail.id), class:"text-blue-500" %>
      <% end %>
    </div>
    <% if @cocktail.images.attached? %>
      <div class=" swiper mySwiper" data-controller="swiper">
        <div class="swiper-wrapper">
          <% @cocktail.images.each do |image|%>
            <div class="swiper-slide">
              <%= image_tag image.url , class:"w-full rounded-md max-w-md mx-auto"%>
            </div>
          <% end %>
        </div>
        <div class="swiper-pagination"></div>
      </div>
    <% else %>
      <%= image_tag "https://fakeimg.pl/300x300", class:"w-60 mx-auto rounded-md"%>
    <% end %>
  </div>
  <div class="lg:mx-4">
    <div data-controller="add-like" class="flex items-center gap-2">
      <div class="flex items-center gap-2">
        <button 
          data-action="click->add-like#add_like"
          data-add-like-target="link"
          data-cocktail-id= <%= @cocktail.id%>
          class="transition-all duration-300 ease-in-out rounded-sm  hover:scale-110"
          >
          <%= image_tag "icons/heart.svg"%>
        </button>
        <p data-add-like-target="like_count"></p>
      </div>
      <%= image_tag "icons/comment.svg"%>
    </div>
    <div>
      <h1 class="font-bold "><%= @cocktail.name %> </h1>
      <%= link_to @cocktail.user.profile.name, profile_path(@cocktail.user.profile.id), class:"text-gray-400 hover:text-white"%>
    </div>
    <p class="my-4">
      <span class="font-bold ">Base :</span>
      <%= @cocktail.base_wine%>
    </p>
    <p class="my-4">
      <span class="font-bold ">Skill :</span>
      <%= @cocktail.skill%>
    </p>
    <div>
      <%= @cocktail.introduce%>
    </div>
  </div>
  <button>留言</button>
  <div>
    <%= turbo_frame_tag "comments" do %>
      <%= render @cocktail.comments %>
    <% end %>
    <%= render "comments/new"%>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" defer></script>