config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  scope :users do
    resources :profiles, except: %i[index] do
      resources :collects, only: %i[create destroy]
    end
  end
  
  # articles
  resources :articles
  
  # comments 
  resources :cocktails do
    resources :comments
  end

  # classic cocktails
  resources :classic_cocktails

  # like
  get "likes/:cocktail_id", to: "likes#show"
  post "likes", to: "likes#create"

  # user location
  post "/get_user_location", to: "pages#get_user_location"

  # outher
  get "setting", to: "users#setting"
  get "cocktail_map", to: "pages#cocktail_map"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  before_create :generate_uuid_v7

  private

  def generate_uuid_v7
    return if self.class.attribute_types["id"].type != :uuid

    self.id ||= UUID7.generate
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, :category, :content, presence: true
end

app/models/classic_cocktail.rb
class ClassicCocktail < ApplicationRecord
  has_one_attached :image
  def self.ransackable_attributes(_auth_object = nil)
    %w[base_wine created_at garnish glass history id id_value ingredient method name skill updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_rich_text :introduce
  has_many_attached :images
  has_many :likes
  has_many :comments
  belongs_to :user

  def self.ransackable_attributes(_auth_object = nil)
    %w[name base_wine]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/models/collect.rb
class Collect < ApplicationRecord
  belongs_to :profile
  belongs_to :user

  validates :user_id, uniqueness: { scope: :profile_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail

  validates :user_id, uniqueness: { scope: :cocktail_id, message: "has already liked this cocktail" }
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_one_attached :avatar
  belongs_to :user
  has_many :collects
  has_many :followers, through: :collects, source: :user

  def address_info
    [["請選擇", nil], %w[台北市 台北市], %w[新北市 新北市], %w[桃園市 桃園市], %w[台中市 台中市], %w[台南市 台南市], %w[高雄市 高雄市], %w[新竹縣 新竹縣], %w[苗栗縣 苗栗縣], %w[彰化縣 彰化縣], %w[南投縣 南投縣], %w[雲林縣 雲林縣], %w[嘉義縣 嘉義縣], %w[屏東縣 屏東縣], %w[宜蘭縣 宜蘭縣], %w[花蓮縣 花蓮縣], %w[台東縣 澎湖縣], %w[金門縣 金門縣], %w[連江縣 連江縣], %w[基隆市 基隆市], %w[新竹市 新竹市], %w[嘉義市 嘉義市]]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :cocktails
  has_many :likes
  has_many :comments
  has_many :collects
  has_many :followed_profiles, through: :collects, source: :profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    user ||= User.create(full_name: data["name"],
                         email: data["email"],
                         password: Devise.friendly_token[0, 20],)
    user
  end
end

app/controllers/classic_cocktails_controller.rb
class ClassicCocktailsController < ApplicationController
  before_action :set_classic_cocktail, only: %i[show edit update destroy]

  def index
    @q = ClassicCocktail.ransack(params[:q])
    @classic_cocktails = @q.result.order(name: :asc)
  end

  def show; end

  def new; end

  def create; end

  def edit; end

  def update
    if @classic_cocktail.update(classic_cocktail_params)
      redirect_to @classic_cocktail, notice: "Classic cocktail was successfully updated."
    else
      flash.now[:alert] = @classic_cocktail.errors.full_messages
      render :edit
    end
  end

  def destroy; end

  private

  def classic_cocktail_params
    params.require(:classic_cocktail).permit(:name, :skill, :garnish, :glass, :history, :ingredient, :method, :image)
  end

  def set_classic_cocktail
    @classic_cocktail = ClassicCocktail.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :check_current_user, only: [:create]

  def show
    cocktail = Cocktail.find(params[:cocktail_id])
    likes_count = cocktail.likes.count
    liked = cocktail.likes.exists?(user_id: current_user.id) if current_user.present?
    render json: {
      likes_count: likes_count,
      current_user_liked: liked,
    }
  end

  def create
    @like = Like.new(user_id: current_user.id, cocktail_id: params[:cocktail_id])
    if @like.save
    else
      destroy
    end
    show
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id)
    @like.delete
  end

  private

  def check_current_user
    redirect_to new_user_session_path if current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_profile, only: :home
  def home
    @cocktails = Cocktail.all
  end

  def cocktail_map; end

  def check_profile
    return if current_user.nil?
    return if current_user.profile.present?

    name = current_user.full_name || current_user.email
    current_user.create_profile(name: unique_name(name))
  end

  private

  def unique_name(name)
    "#{name}-#{SecureRandom.hex(4)}" # 在名称后面加上随机字符串
  end

  def default_avatar
    "https://cdn-icons-png.flaticon.com/512/149/149071.png"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, olny: %i[show setting]
  before_action :authenticate_user!

  def show; end

  def setting; end

  private

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/classic_cocktails_helper.rb
module ClassicCocktailsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/collects_helper.rb
module CollectsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def search_bars(api_key, location, radius = 5000)
    url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=#{api_key}&location=#{location}&radius=#{radius}&keyword=bar")
    response = Net::HTTP.get(url)
    data = JSON.parse(response)
    puts data["results"]

    if data["status"] == "OK"
      data["results"]
    else
      []
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/classic_cocktails/_form.html.erb
<%= form_with(model: @classic_cocktail) do |f|%>
  <div class="mt-4 ">
    <%= f.label :image, "相片"%>
    <%= f.file_field :image, class:"block"%>
  </div>
  <div class="mt-4 ">
    <%= f.label :name, "名稱"%>
    <%= f.text_field :name, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <div class="mt-4 ">
    <%= f.label :history, "起源"%>
    <%= f.text_area :history, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <div class="mt-4 ">
    <%= f.label :skill, "手法"%>
    <%= f.select :skill, [["build", "build"], ["stir", "stir"], ["shake", "shake"]], {}, class: "block w-full rounded-md p-2 text-black" %>
  </div>
  <div class="mt-4 ">
    <%= f.label :garnish, "裝飾"%>
    <%= f.text_field :garnish, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <div class="mt-4 " >
    <%= f.label :glass, "杯型"%>
    <%= f.select :glass, [["Martini", "Martini"], ["Old Fashioned", "Old Fashioned"], ["Highball", "Highball"], ["Shot", "Shot"], ["Margarita", "Margarita"], ["Wine", "Wine"], ["Champagne", "Champagne"]], {}, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <div class="mt-4 " >
    <%= f.label :base_wine, "基酒"%>
    <%= f.text_field :base_wine, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <div class="mt-4 ">
    <%= f.label :ingredient, "材料"%>
    <%= f.text_field :ingredient, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <div class="mt-4 ">
    <%= f.label :method, "作法"%>
    <%= f.text_area :name, class:"block w-full rounded-md p-2 text-black"%>
  </div>
  <%= f.submit "新增", class:"w-full p-2 bg-amber-900 my-4 cursor-pointer hover:bg-amber-800"%>
<% end %> 

app/views/classic_cocktails/edit.html.erb
<div>
  <%= link_to :back do %>
    <%= image_tag "arrow_back_icon.png", class:"invert"%>
  <% end %>
  <h2>Edit Classic Cocktail</h2>
  <%= render "form"%>
</div>

app/views/classic_cocktails/index.html.erb
<div>
  <h1>經典調酒</h1>
  <div class="my-4">
    <%= search_form_for @q, class:"flex gap-2 items-end" do |f|%>
      <div>
        <%= f.label :base_wine_cont, "選擇基酒"%>
        <%= f.select :base_wine_cont, [["Gin", "Gin"], ["Whisky", "Whisky"], ["Vodka", "Vodka"], ["Brandy", "Brandy"], ["Tequila", "Tequila"], ["Rum", "Rum"]]  ,{}, class:"w-full rounded-md p-2 text-black"%>
      </div>
      <%= f.search_field :name_cont, placeholder:"搜尋名稱", class:"w-full rounded-md p-2 text-black"%>
      <button>
        <%= image_tag "search.png", class:"w-12 md:w-14 lg:w-16"%>
      </button>
    <% end %>
  </div>
  <div>
    <% if @classic_cocktails.length == 0%>
      <h2 class="text-center ">oppps! <br>
        找不到資料</h2>
    <% end %>
    <% @classic_cocktails.each do |cocktail|%>
      <%= link_to classic_cocktail_path(cocktail.id), class:"block rounded-md p-2 border my-4" do %>
        <%= cocktail.name%>
      <% end %>
    <% end %>
  </div>
</div>

app/views/classic_cocktails/new.html.erb
<div>
  <h2>New Classic Cocktail</h2>
  <%= render "form"%>
</div>

app/views/classic_cocktails/show.html.erb
<div class="show_classic_cocltail">
  <%= link_to :back, aria: {label:"back link"}, class:"w-fit block hover:scale-125" do%>
    <%= image_tag "arrow_back_icon.png", alt:"back icon"%>
  <% end %>
  <div>
    <h2>
      <%= @classic_cocktail.name%>
    </h2>
    <%= link_to "編輯", edit_classic_cocktail_path(@classic_cocktail.id), class:"text-blue-500" if current_user && current_user.role === "admin"%>
    <div class="my-4" data-controller="upload-image">
      <div data-action="click->upload-image#selectImage">
        <% if @classic_cocktail.image.attached?%>
          <%= image_tag @classic_cocktail.image%>
        <% else %>
          <%= image_tag "https://fakeimg.pl/1920x1080/", alt:"#{@classic_cocktail.name} image", class:"w-full rounded-md mx-auto md:w-10/12 lg:w-8/12 xl:w-6/12"%>
        <% end %>
      </div>
      <% if current_user && current_user.role === "admin" %>
        <%= form_with(model: @classic_cocktail, class:"hidden", data: {turbo: false, turbo_method: :patch, upload_image_target: "form"}) do |f| %>
          <%= f.file_field :image, data: { upload_image_target: "input", action: "change->upload-image#uploadImage"} %>
        <% end %>
      <% end %>
    </div>
    <div class="my-4">
      <h3>History:</h3>
      <p >
        <%= @classic_cocktail.history%>
      </p>
    </div>
    <div class="my-4">
      <h3>Ingredient:</h3>
      <%= @classic_cocktail.ingredient.gsub("\n", "<br>").html_safe%>
    </div>
    <div class="my-4">
      <h3>Skill:</h3>
      <p >
        <%= @classic_cocktail.skill%>
      </p>
    </div>
    <div class="my-4">
      <h3>Garnish:</h3>
      <p >
        <%= @classic_cocktail.garnish%>
      </p>
    </div>
    <div class="my-4">
      <h3>Glass:</h3>
      <p >
        <%= @classic_cocktail.glass%>
      </p>
    </div>
    <div class="my-4">
      <h3>Method:</h3>
      <p >
        <%= @classic_cocktail.method.gsub("\n", "<br>").html_safe %>
      </div>
    </p>
  </div>
</div>